config/routes.rb
Rails.application.routes.draw do

  get "/", controller: "home", action: "index", as: "home"
  get "/contact", controller: "home", action: "contact"
  get "/about", controller: "home", action: "contact"
  get "/track/:param_title", controller: "tracks", action: "track", as: :track
  post "/search", controller: "home", action: "search"

end

app/models/track.rb
class Track
  attr_accessor :title, :band, :cover 

  def initialize title, band="Metallica", cover=""
    @title = title 
    @band = band 
    @cover = cover 
  end

  def to_param
    @title.parameterize
  end

  def self.all
    [
      Track.new("Enter Sandman", "Metallica", "http://www.earlytorise.com/wp-content/uploads/2009/10/metallica-enter-sandman-dirty-funker-remixs.jpg"),
      Track.new("Lol", "Blog 27"),
      Track.new("Hello"),
      Track.new("Enter Sandman", "Iron"),
    ] 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index 
    @tracks = Track.all
  end 

  def search
    title = Regexp.new(params[:title].downcase)
    band = Regexp.new(params[:band].downcase)

    @tracks = Track.all.select do |track| 
      if params[:band].present? 
        track.band.downcase =~ band
      else
        track.title.downcase =~ title
      end
    end
    render "home/index"
  end

  def contact
    
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def track
    @track = Track.all.find do |track|
      track.to_param == params[:param_title] 
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
RUBIO 
<%= form_tag "/search" do %>
  <%= label_tag :title %>
  <%= text_field_tag :title %>
  <%= label_tag :band %>
  <%= text_field_tag :band %>
<%= submit_tag "Search" %>
<% end %>
<br>
<% @tracks.each do |track| %> 
  <%= link_to track.title, track_path(track) %>
  <%= track_path(track.to_param, category: "metal") %>
  <%= image_tag track.cover, heigth: 80, width: 80 %> <%= track.title %> - <%= track.band %> <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tracks/track.html.erb
<%= link_to "Home", home_path %>
track
<%= @track.title %>